const QUESTIONS = [
   'Quel est ton artiste préféré ?',
   'Quel livre t’a le plus marqué ?',
   'Le cinéma est-il un art majeur ?',
   'La musique influence-t-elle notre humeur ?',
   'Faut-il séparer l’œuvre de l’artiste ?',
   'Quel tableau célèbre aimerais-tu voir en vrai ?',
   'Les films sont-ils meilleurs que les livres ?',
   'Les jeux vidéo sont-ils une forme d’art ?',
   'Faut-il protéger les œuvres d’art contre les interprétations modernes ?',
   'La démocratie est-elle le meilleur système politique ?',
   'Faut-il légaliser toutes les drogues ?',
   'L’argent fait-il le bonheur ?',
   'Doit-on toujours dire la vérité ?',
   'Le travail est-il une valeur essentielle ?',
   'Peut-on rire de tout ?',
   'L’éducation doit-elle être totalement gratuite ?',
   'Les réseaux sociaux nuisent-ils aux relations humaines ?',
   'Faut-il interdire la publicité pour des raisons éthiques ?',
   'La justice est-elle réellement équitable ?',
   'Qu’est-ce que le bonheur ?',
   'L’Homme est-il fondamentalement bon ou mauvais ?',
   'Peut-on être libre dans une société ?',
   'L’existence a-t-elle un sens ?',
   'Le destin existe-t-il ?',
   'A-t-on besoin des autres pour être heureux ?',
   'L’intelligence est-elle innée ou acquise ?',
   'Faut-il apprendre à pardonner tout ?',
   'Le passé définit-il qui nous sommes ?',
   'La peur est-elle une force ou une faiblesse ?',
   'Les avancées technologiques sont-elles toujours bénéfiques ?',
   'L’intelligence artificielle remplacera-t-elle les humains ?',
   'Faut-il avoir peur du transhumanisme ?',
   'La conquête spatiale est-elle essentielle ?',
   'La science peut-elle tout expliquer ?',
   'Faut-il limiter la recherche sur l’ADN humain ?',
   'La technologie rapproche-t-elle ou isole-t-elle les gens ?',
   'Peut-on vivre sans smartphone aujourd’hui ?',
   'L’Homme pourra-t-il un jour devenir immortel ?',
   'L’écologie doit-elle primer sur le progrès technologique ?',
   'L’histoire est-elle objective ?',
   'Pourquoi l’Homme répète-t-il toujours les mêmes erreurs ?',
   'La colonisation a-t-elle encore des impacts aujourd’hui ?',
   'Peut-on juger le passé avec les valeurs du présent ?',
   'La guerre est-elle parfois justifiable ?',
   'L’utopie politique est-elle possible ?',
   'La mondialisation est-elle une bonne chose ?',
   'Un monde sans frontières est-il envisageable ?',
   'Doit-on encore honorer les héros du passé ?',
   'La neutralité est-elle possible en politique ?',
   'La famille est-elle plus importante que les amis ?',
   'Peut-on être heureux seul ?',
   'Faut-il toujours faire des compromis en amour ?',
   'Est-il plus important d’être respecté ou aimé ?',
   'L’amitié homme-femme est-elle possible ?',
   'Faut-il toujours écouter son instinct ?',
   'La jalousie est-elle une preuve d’amour ?',
   'La politesse est-elle essentielle dans la société ?',
   'Peut-on être trop gentil ?',
   'L’amour dure-t-il vraiment toujours ?',
   'Faut-il aimer son travail pour être heureux ?',
   'La réussite se mesure-t-elle à l’argent gagné ?',
   'Est-il possible de réussir seul ?',
   'Le travail d’équipe est-il toujours efficace ?',
   'Les diplômes sont-ils nécessaires pour réussir ?',
   'Faut-il prendre des risques pour réussir ?',
   'L’échec est-il une étape obligatoire vers le succès ?',
   'La méritocratie existe-t-elle vraiment ?',
   'Faut-il faire un travail qui a du sens ou qui rapporte de l’argent ?',
   'Travailler moins rend-il plus heureux ?',
   'L’Homme est-il responsable du changement climatique ?',
   'Peut-on concilier progrès économique et écologie ?',
   'Faut-il interdire la viande pour sauver la planète ?',
   'L’énergie nucléaire est-elle une solution écologique ?',
   'Les petits gestes individuels ont-ils un réel impact sur l’environnement ?',
   'Faut-il bannir complètement le plastique ?',
   'La décroissance est-elle une solution viable ?',
   'La nature appartient-elle à l’Homme ou l’inverse ?',
   'Les zoos sont-ils une bonne ou une mauvaise chose ?',
   'Les catastrophes naturelles sont-elles une punition de la nature ?',
   'Faut-il revoir entièrement le système éducatif ?',
   'L’école doit-elle apprendre à penser ou à obéir ?',
   'Les notes sont-elles une bonne méthode d’évaluation ?',
   'L’éducation à la maison est-elle une meilleure alternative ?',
   'L’apprentissage par l’expérience est-il plus efficace que la théorie ?',
   'Faut-il enseigner la philosophie dès le plus jeune âge ?',
   'L’éducation devrait-elle être la même pour tous ?',
   'Les diplômes sont-ils un gage d’intelligence ?',
   'L’école prépare-t-elle réellement à la vie ?',
   'Faut-il apprendre plusieurs langues dès l’enfance ?',
   'Un enfant a-t-il besoin de deux parents pour bien grandir ?',
   'Faut-il être ami avec ses enfants ?',
   'La famille est-elle une obligation ou un choix ?',
   'Les parents doivent-ils imposer des valeurs à leurs enfants ?',
   'Éduquer un enfant est-il plus difficile aujourd’hui qu’avant ?',
   'La fessée est-elle une méthode d’éducation acceptable ?',
   'Un enfant peut-il être autonome dès son plus jeune âge ?',
   'Avoir des enfants est-il nécessaire pour être accompli ?',
   'Faut-il protéger les enfants de toutes formes de frustration ?',
   'Les rôles père/mère doivent-ils être interchangeables ?',
   'Un jour, vivrons-nous sur Mars ?',
   'Les robots remplaceront-ils les humains dans tous les métiers ?',
   'Peut-on un jour télécharger sa conscience dans un ordinateur ?',
   'La téléportation sera-t-elle une réalité ?',
   'Les extraterrestres existent-ils ?',
   'Si on trouvait une autre planète habitable, faudrait-il y aller ?',
   'Le voyage dans le temps sera-t-il possible ?',
   'Les clones humains devraient-ils avoir des droits ?',
   'L’humanité doit-elle chercher à vivre éternellement ?',
   'Le futur sera-t-il meilleur ou pire que le présent ?',
   'Peut-on être heureux sans faire le bien ?',
   'Faire une bonne action par intérêt, est-ce toujours moral ?',
   'L’Homme est-il fondamentalement égoïste ?',
   'Doit-on toujours respecter les lois, même injustes ?',
   'La fin justifie-t-elle les moyens ?',
   'Existe-t-il un bien et un mal absolus ?',
   'Aider les autres est-il un devoir moral ?',
   'La vengeance est-elle légitime dans certains cas ?',
   'Faut-il privilégier le bien du plus grand nombre ou l’individu ?',
   'Le pardon est-il une preuve de faiblesse ou de force ?',
   'L’alcool devrait-il être interdit comme d’autres drogues ?',
   'La médecine alternative est-elle efficace ?',
   'Faut-il limiter le temps passé sur les écrans pour sa santé mentale ?',
   'Le sport est-il obligatoire pour être en bonne santé ?',
   'Peut-on être heureux sans être en bonne santé ?',
   'Le bien-être mental est-il plus important que la santé physique ?',
   'La chirurgie esthétique est-elle une bonne ou une mauvaise chose ?',
   'Vieillir est-il une maladie à combattre ?',
   'Manger bio est-il vraiment meilleur pour la santé ?',
   'Les avancées médicales doivent-elles être accessibles à tous, quel que soit le coût ?',
   'Peut-on être spirituel sans être religieux ?',
   'Les religions ont-elles encore leur place dans la société moderne ?',
   'Faut-il croire en quelque chose pour donner un sens à sa vie ?',
   'Les miracles existent-ils vraiment ?',
   'La religion divise-t-elle plus qu’elle ne rassemble ?',
   'La prière a-t-elle un réel pouvoir ?',
   'L’athéisme est-il aussi une croyance ?',
   'Peut-on prouver l’existence de Dieu ?',
   'Toutes les religions se valent-elles ?',
   'La science finira-t-elle par remplacer la foi ?',
   'Le temps est-il une illusion ?',
   'Pourquoi avons-nous l’impression que le temps passe plus vite en vieillissant ?',
   'Peut-on vraiment vivre dans le présent ?',
   'Le passé influence-t-il trop notre présent ?',
   'L’avenir est-il déjà écrit ?',
   'Revivre un moment de son passé, est-ce une bonne idée ?',
   'Nos souvenirs sont-ils fiables ?',
   'Pourquoi avons-nous peur de l’avenir ?',
   'Vieillir, est-ce forcément décliner ?',
   'L’ennui est-il une perte de temps ou un moment nécessaire ?',
   'L’amour est-il rationnel ou purement instinctif ?',
   'Un couple doit-il tout se dire ?',
   'La jalousie est-elle une preuve d’amour ou un manque de confiance ?',
   'Faut-il croire en l’amour éternel ?',
   'Les opposés s’attirent-ils vraiment ?',
   'Peut-on aimer plusieurs personnes en même temps ?',
   'L’amitié peut-elle se transformer en amour ?',
   'Faut-il toujours essayer de sauver un couple en crise ?',
   'Le mariage est-il encore une institution utile ?',
   'Un couple peut-il durer sans désir physique ?',
   'La peine de mort est-elle justifiable dans certains cas ?',
   'La prison permet-elle vraiment de réhabiliter les criminels ?',
   'La justice est-elle trop influencée par l’opinion publique ?',
   'Vaut-il mieux libérer un coupable ou condamner un innocent ?',
   'La loi doit-elle évoluer en fonction des mœurs ou rester immuable ?',
   'Peut-on dire que la loi est forcément juste ?',
   'Faut-il protéger la liberté d’expression à tout prix ?',
   'La légitime défense est-elle un argument valable en justice ?',
   'Les criminels ont-ils droit à une seconde chance ?',
   'La corruption est-elle inévitable dans un système judiciaire ?',
   'Peut-on vraiment réussir sans piston ni privilèges ?',
   'Faut-il instaurer un revenu universel ?',
   'Le travail est-il une valeur essentielle dans une société moderne ?',
   'L’argent corrompt-il forcément ?',
   'Est-il moral de gagner de l’argent sans travailler ?',
   'L’auto-entrepreneuriat est-il l’avenir du travail ?',
   'Travailler moins signifie-t-il être moins productif ?',
   'Peut-on être riche et éthique à la fois ?',
   'Faut-il taxer davantage les grandes fortunes ?',
   'La mondialisation est-elle une menace ou une opportunité économique ?',
   'Pourquoi avons-nous peur du regard des autres ?',
   'La routine est-elle ennemie du bonheur ?',
   'Peut-on vraiment changer de personnalité ?',
   'La générosité est-elle toujours désintéressée ?',
   'L’ennui est-il nécessaire pour la créativité ?',
   'Pourquoi l’être humain a-t-il besoin de rituels ?',
   'Peut-on vivre heureux sans prendre de risques ?',
   'La solitude choisie est-elle une liberté ou une fuite ?',
   'Est-on toujours responsable de nos émotions ?',
   'Peut-on réellement contrôler ses pensées ?',
   'L’intelligence émotionnelle est-elle plus importante que l’intelligence académique ?',
   'L’apprentissage devrait-il être personnalisé pour chaque élève ?',
   'Faut-il enseigner l’échec à l’école ?',
   'Les compétences pratiques sont-elles sous-estimées dans l’éducation ?',
   'L’école devrait-elle enseigner la gestion de l’argent et des émotions ?',
   'Apprend-on mieux en autodidacte qu’avec un professeur ?',
   'L’éducation doit-elle avant tout former des travailleurs ou des citoyens ?',
   'Les élèves devraient-ils avoir plus de liberté dans leur apprentissage ?',
   'La compétition à l’école est-elle bénéfique ou nuisible ?',
   'Le système scolaire actuel est-il obsolète ?',
   'Peut-on être un bon parent sans modèle familial solide ?',
   'Les enfants doivent-ils avoir des limites strictes ou être libres d’explorer ?',
   'L’éducation traditionnelle est-elle dépassée ?',
   'Peut-on vraiment éviter de reproduire l’éducation que l’on a reçue ?',
   'Les parents doivent-ils être des modèles parfaits ?',
   'La technologie facilite-t-elle ou complique-t-elle l’éducation des enfants ?',
   'Un enfant peut-il être épanoui sans fratrie ?',
   'Le rôle des grands-parents est-il aussi important que celui des parents ?',
   'Faut-il être sévère pour être respecté par ses enfants ?',
   'Les enfants doivent-ils apprendre à gérer l’échec dès le plus jeune âge ?',
   'Le libre arbitre existe-t-il vraiment ?',
   'Peut-on être soi-même sans être influencé par les autres ?',
   'Le bonheur est-il une quête ou un état d’esprit ?',
   'Nos choix sont-ils dictés par la raison ou par nos émotions ?',
   'La peur est-elle le moteur de l’action ou son frein ?',
   'Est-il préférable d’être optimiste ou réaliste ?',
   'L’identité d’une personne change-t-elle au fil du temps ?',
   'Peut-on atteindre la sagesse sans souffrance ?',
   'Sommes-nous les seuls responsables de notre destin ?',
   'La vérité est-elle toujours préférable au mensonge ?',
   'L’intelligence artificielle aura-t-elle un jour une conscience ?',
   'La robotisation va-t-elle détruire plus d’emplois qu’elle n’en crée ?',
   'Faut-il craindre la surveillance généralisée ?',
   'La conquête spatiale justifie-t-elle son coût ?',
   'Le progrès scientifique doit-il être limité par l’éthique ?',
   'La technologie nous rend-elle plus intelligents ou plus dépendants ?',
   'Devrait-on interdire certaines technologies avant même qu’elles existent ?',
   'La science peut-elle réellement tout expliquer ?',
   'Le transhumanisme est-il une évolution naturelle de l’humanité ?',
   'Peut-on vivre dans un monde 100 % numérique ?',
   'L’écologie est-elle un luxe de pays riches ?',
   'Le réchauffement climatique est-il irréversible ?',
   'Faut-il interdire les voyages en avion pour sauver la planète ?',
   'Les actions individuelles suffisent-elles à changer le monde ?',
   'La nature a-t-elle des droits ?',
   'Devrait-on limiter le nombre d’enfants pour préserver la planète ?',
   'Faut-il interdire les fast-foods pour des raisons écologiques ?',
   'L’éco-anxiété est-elle justifiée ?',
   'Peut-on concilier urbanisation et respect de l’environnement ?',
   'La décroissance est-elle viable sur le long terme ?',
   'Peut-on choisir d’être heureux ?',
   'L’intuition est-elle plus fiable que la logique ?',
   'Le stress est-il toujours négatif ?',
   'Nos souvenirs sont-ils une version fidèle du passé ?',
   'Peut-on contrôler ses émotions ou seulement les gérer ?',
   'La peur est-elle notre plus grand ennemi ?',
   'Pourquoi avons-nous besoin de reconnaissance ?',
   'Les introvertis sont-ils désavantagés dans la société ?',
   'L’intelligence émotionnelle est-elle plus importante que le QI ?',
   'Peut-on être heureux sans jamais ressentir de tristesse ?',
   'Pourquoi avons-nous besoin de nous comparer aux autres ?',
   'Le silence en dit-il plus que les mots ?',
   'La première impression est-elle toujours la bonne ?',
   'Les réseaux sociaux renforcent-ils ou affaiblissent-ils nos liens sociaux ?',
   'Peut-on vraiment comprendre quelqu’un d’autre ?',
   'Faut-il toujours répondre aux provocations ?',
   'Peut-on convaincre quelqu’un de changer d’avis ?',
   'Faut-il toujours écouter les conseils des autres ?',
   'Pourquoi est-il parfois difficile de demander pardon ?',
   'La communication non verbale est-elle plus puissante que les mots ?',
   'L’intelligence artificielle surpassera-t-elle l’humanité ?',
   'Faut-il avoir peur des avancées en biotechnologie ?',
   'Les voitures volantes deviendront-elles une réalité ?',
   'Les machines pourront-elles un jour ressentir des émotions ?',
   'Le métavers remplacera-t-il le monde réel ?',
   'Faut-il craindre une guerre homme-machine ?',
   'L’exploration spatiale doit-elle être une priorité ?',
   'Peut-on imaginer une société entièrement automatisée ?',
   'Le clonage humain est-il une évolution naturelle de la science ?',
   'Les humains du futur seront-ils génétiquement modifiés ?',
   'Une langue influence-t-elle notre façon de penser ?',
   'L’anglais doit-il devenir la langue universelle ?',
   'La traduction peut-elle vraiment transmettre toutes les nuances d’une langue ?',
   'Faut-il préserver les langues en voie de disparition ?',
   'Apprendre une langue change-t-il notre personnalité ?',
   'La diversité culturelle est-elle en danger ?',
   'Peut-on comprendre une culture sans parler sa langue ?',
   'Faut-il enseigner plus d’une langue dès la maternelle ?',
   'L’accent influe-t-il sur l’image que l’on donne aux autres ?',
   'Les langues évoluent-elles toujours vers le mieux ?',
   'Les loisirs sont-ils une perte de temps ou une nécessité ?',
   'Lire est-il meilleur que regarder des films ?',
   'Peut-on devenir accro au travail comme à un loisir ?',
   'La passion peut-elle devenir une obsession ?',
   'Les vacances sont-elles essentielles pour le bien-être ?',
   'Les jeux de société sont-ils plus enrichissants que les jeux vidéo ?',
   'Peut-on être heureux sans avoir de passion ?',
   'Le sport est-il un loisir ou une discipline ?',
   'La télévision a-t-elle encore un avenir face aux plateformes de streaming ?',
   'Faut-il limiter le temps passé sur les écrans ?',
   'Internet nous rend-il plus intelligents ou plus dépendants ?',
   'L’anonymat en ligne est-il une bonne ou une mauvaise chose ?',
   'Le télétravail est-il l’avenir du travail ?',
   'Les influenceurs ont-ils trop d’impact sur la société ?',
   'La surinformation nous empêche-t-elle de réfléchir ?',
   'La vie privée existe-t-elle encore à l’ère numérique ?',
   'Peut-on un jour vivre sans argent grâce aux technologies ?',
   'Les algorithmes dirigent-ils nos vies ?',
   'L’IA peut-elle remplacer les artistes ?',
   'Les deepfakes sont-ils un danger pour la vérité ?',
   'Pourquoi l’Histoire est-elle toujours écrite par les vainqueurs ?',
   'Devrait-on enseigner toutes les erreurs du passé, même les plus sombres ?',
   'L’Histoire se répète-t-elle inévitablement ?',
   'Les commémorations sont-elles essentielles ou inutiles ?',
   'Peut-on vraiment comprendre une époque sans l’avoir vécue ?',
   'Effacer un personnage historique controversé de l’Histoire est-il justifiable ?',
   'Les légendes historiques sont-elles plus puissantes que les faits ?',
   'L’Histoire nous apprend-elle vraiment des leçons ?',
   'Les musées doivent-ils restituer les œuvres volées ?',
   'L’Histoire est-elle un outil de manipulation politique ?',
   'La liberté a-t-elle des limites ?',
   'Faut-il sacrifier une partie de sa liberté pour plus de sécurité ?',
   'Peut-on être libre dans une société où tout est réglementé ?',
   'Le contrôle des masses est-il inévitable ?',
   'La censure est-elle parfois nécessaire ?',
   'La surveillance gouvernementale peut-elle être justifiée ?',
   'L’autocensure est-elle une forme de soumission ?',
   'Sommes-nous plus libres aujourd’hui qu’il y a 100 ans ?',
   'La propagande existe-t-elle encore aujourd’hui ?',
   'La peur est-elle un outil de contrôle social ?',
   'Un monde sans argent est-il possible ?',
   'Une société sans crime pourrait-elle exister ?',
   'L’égalité parfaite est-elle un idéal ou un mythe ?',
   'Le bonheur pour tous est-il possible ?',
   'Peut-on créer une société sans conflits ?',
   'Une intelligence artificielle pourrait-elle gouverner un pays ?',
   'La fin des inégalités est-elle réalisable ?',
   'Les dystopies de la science-fiction peuvent-elles devenir réelles ?',
   'La paix mondiale est-elle un objectif atteignable ?',
   'L’homme peut-il un jour dépasser sa propre nature ?',
   'Pourquoi certaines personnes croient-elles aux théories du complot ?',
   'Les fake news sont-elles une menace pour la démocratie ?',
   'Peut-on prouver que la Terre est ronde à quelqu’un qui refuse d’y croire ?',
   'Faut-il interdire la diffusion de fausses informations ?',
   'L’esprit critique s’apprend-il ?',
   'Les gouvernements nous cachent-ils la vérité ?',
   'Pourquoi aimons-nous les mystères et l’inexpliqué ?',
   'Y a-t-il une limite entre scepticisme et paranoïa ?',
   'Le paranormal est-il une réalité ou une illusion ?',
   'L’ésotérisme est-il un refuge face à un monde rationnel ?',
   'Peut-on vraiment se connaître soi-même ?',
   'Nos échecs nous définissent-ils plus que nos réussites ?',
   'La gratitude change-t-elle notre perception du monde ?',
   'L’instant présent est-il le seul qui compte ?',
   'Pourquoi avons-nous parfois peur d’être seuls avec nos pensées ?',
   'Les regrets sont-ils inévitables ?',
   'Le voyage change-t-il réellement une personne ?',
   'Nos rêves ont-ils un sens caché ?',
   'Faut-il suivre son cœur ou sa raison ?',
   'La souffrance rend-elle plus fort ?',
   'La vie est-elle un hasard ou a-t-elle un but ?',
   'L’égoïsme est-il toujours négatif ?',
   'Le monde va-t-il mieux ou pire qu’avant ?',
   'La curiosité est-elle toujours une qualité ?',
   'L’être humain est-il capable de sagesse collective ?',
   'Faut-il toujours tout remettre en question ?',
   'L’ennui peut-il être créatif ?',
   'La compétition nous rend-elle meilleurs ?',
   'Pourquoi avons-nous besoin de raconter des histoires ?',
   'Un monde sans mensonge serait-il vivable ?',
   'Le hasard existe-t-il vraiment ?',
   'L’optimisme est-il une forme d’aveuglement ?',
   'Pourquoi cherchons-nous toujours à donner un sens à tout ?',
   'Peut-on être heureux sans aucun objectif dans la vie ?',
   'L’amour est-il la réponse à tout ?',
];

export const getDailyQuestion = (): string => {
   const now = new Date();

   const start = new Date(now.getFullYear(), 0, 0);
   const diff = now.getTime() - start.getTime();
   const oneDay = 1000 * 60 * 60 * 24;
   const dayOfYear = Math.floor(diff / oneDay);

   const questionIdx = (dayOfYear - 1) % QUESTIONS.length;

   return QUESTIONS[questionIdx];
};
