name: Deploy

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    production:
        name: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  cache: yarn
            - run: yarn install
            - run: yarn build
            # - name: Deploy
            #   uses: burnett01/rsync-deployments@5.1
            #   with:
            #       switches: -avzr --delete
            #       path: build/
            #       remote_path: ${{ secrets.DIR }}
            #       remote_host: ${{ secrets.HOST }}
            #       remote_port: ${{ secrets.PORT }}
            #       remote_user: ${{ secrets.USER }}
            #       remote_key: ${{ secrets.SSHKEY }}
            - run: echo "${{ secrets.SSHKEY }}" > key.pem
            - run: chmod 600 key.pem
            - run: rsync -Pav -e "ssh -i key.pem" build/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/build/
            - run: rsync -Pav -e "ssh -i key.pem" node_modules/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/node_modules/
