name: Deploy

on:
   push:
      branches:
         - master
   pull_request:

jobs:
   eslint:
      name: Check eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:eslint

   prettier:
      name: Check prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:prettier

   typescript:
      name: Check typescript
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn check:typescript

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
              cache: yarn
         - run: yarn install
         - run: yarn tests:ci

   deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [unit_tests]
      if: github.ref == 'refs/heads/master'
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.11.0'
         - run: yarn install
         - run: yarn build
         - run:
              echo "DISCORD_CLIENT_ID_DEVELOPMENT=${{ secrets.DISCORD_CLIENT_ID_DEVELOPMENT }}" >>
              .env
         - run:
              echo "DISCORD_CLIENT_ID_PRODUCTION=${{ secrets.DISCORD_CLIENT_ID_PRODUCTION }}" >>
              .env
         - run: echo "DISCORD_TOKEN_DEVELOPMENT=${{ secrets.DISCORD_TOKEN_DEVELOPMENT }}" >> .env
         - run: echo "DISCORD_TOKEN_PRODUCTION=${{ secrets.DISCORD_TOKEN_PRODUCTION }}" >> .env
         - run:
              echo "DISCORD_DEVELOPMENT_SERVER_ID=${{ secrets.DISCORD_DEVELOPMENT_SERVER_ID }}" >>
              .env
         - run: echo "DISCORD_EMOJIS_SERVER_ID=${{ secrets.DISCORD_EMOJIS_SERVER_ID }}" >> .env
         - run: echo "${{ secrets.SSHKEY }}" > key.pem
         - run: chmod 600 key.pem
         - run:
              rsync -av -e "ssh -i key.pem -o StrictHostKeyChecking=no" . ${{ secrets.USER }}@${{
              secrets.HOST }}:${{ secrets.DIR }}/
         - run:
              ssh -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIR }} && pm2
              startOrRestart pm2.config.json"
