name: Deploy

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    production:
        name: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  cache: yarn
            - name: Deploy
              uses: burnett01/rsync-deployments@5.1
              with:
                  switches: -avzr --delete
                  path: main.js
                  remote_path: main.js
                  remote_host: ${{ secrets.HOST }}
                  remote_port: ${{ secrets.PORT }}
                  remote_user: ${{ secrets.USER }}
                  remote_key: ${{ secrets.SSHKEY }}
