name: Deploy

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    production:
        name: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.11.0"
                  cache: yarn
            - run: yarn install
            - run: yarn build
            - run: echo "${{ secrets.SSHKEY }}" > key.pem
            - run: chmod 600 key.pem
            - run: rsync -Pav -e "ssh -i key.pem -o StrictHostKeyChecking=no" build/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/build/
            - run: rsync -Pav -e "ssh -i key.pem" node_modules/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/node_modules/
            - run: rsync -Pav -e "ssh -i key.pem" package.json ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/package.json
            - run: rsync -Pav -e "ssh -i key.pem" pm2.config.json ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DIR }}/pm2.config.json
            - run: ssh -i key.pem ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.DIR }} && pm2 startOrRestart pm2.config.json"
